### ISSUE TITLE
Hover effect

### ISSUE THREAD

**Issue by Darcy-007** [Roommate-Budget-Helper/RBH-Frontend#49]
All buttons should have hover effect
**Acceptance Criteria**
- [ ]

**Comment by DRSisco** [comment]
What PR closed this? how can I find the code that was added to solve this issue? The main point of adding `closes #issue_number` was so it references back to the issue and you dont have to manually close the issue. 
Now we have no idea where this code is or what PR fixed it. 
This is extremely helpful in the real world as you might want to diagnose which release this issue was fixed in, so you can determine if this issue needs to be reopened or if this is fixed in a later release. 

Also no one was assigned to this issue? So did it magically complete itself?

**Comment by Darcy-007** [comment]
Yes, my bad
